In [ ]:
import numpy as np
import tensorflow as tf

matmul()

$$
\begin{bmatrix}
1 & 0 \\ 
0 & 1 
\end{bmatrix}\cdot \begin{bmatrix}
4 & 1 \\ 
2 & 2 
\end{bmatrix}= \begin{bmatrix}
4 & 1 \\ 
2 & 2
\end{bmatrix}
$$

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8], [9, 10], [11, 12]])
print(np.matmul(a, b))
print(a @ b)
print(np.einsum('ij,jk', a, b))

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [ ]:
c = tf.constant([[1, 2, 3], [4, 5, 6]])
d = tf.constant([[7, 8], [9, 10], [11, 12]])
print(tf.matmul(c, d))
print(c @ d)
print(tf.einsum('ij,jk', c, d))

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


norm()

$$
\left \| A \right \|_{F}= \left [ \sum _{i,j}abs(a_{i,j})^{2} \right ]^{1/2}
$$

In [ ]:
a = np.array([[-4, -3, -2, -1], [1, 2, 3, 4]])
print(np.linalg.norm(a))

7.745966692414834


In [ ]:
b = tf.constant([[-4, -3, -2, -1], [1, 2, 3, 4]], dtype=tf.float16)
print(tf.norm(b))

tf.Tensor(7.746, shape=(), dtype=float16)
