In [1]:
import torch
import numpy as np

matmul()

$$
\begin{bmatrix}
1 & 0 \\ 
0 & 1 
\end{bmatrix}\cdot \begin{bmatrix}
4 & 1 \\ 
2 & 2 
\end{bmatrix}= \begin{bmatrix}
4 & 1 \\ 
2 & 2
\end{bmatrix}
$$

In [15]:
e = torch.tensor([[1, 2, 3], [4, 5, 6]])
f = torch.tensor([[7, 8], [9, 10], [11, 12]])
print(torch.matmul(e, f))
print(e @ f)
print(torch.einsum('ij,jk', e, f))

tensor([[ 58,  64],
        [139, 154]])
tensor([[ 58,  64],
        [139, 154]])
tensor([[ 58,  64],
        [139, 154]])


norm()

$$
\left \| A \right \|_{F}= \left [ \sum _{i,j}abs(a_{i,j})^{2} \right ]^{1/2}
$$

In [20]:
c = torch.tensor([[-4, -3, -2, -1], [1, 2, 3, 4]], dtype=torch.float16)
print(torch.linalg.norm(c))

tensor(7.7461, dtype=torch.float16)
